# Generated by Django 5.2.5 on 2025-09-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0005_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='message_files'),
        ),
    ]
