# Generated by Django 5.2.5 on 2025-09-04 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0006_alter_attachment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
    ]
