# Generated by Django 5.2.5 on 2025-09-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0007_remove_message_file_remove_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_update',
            field=models.BooleanField(default=False),
        ),
    ]
