# Generated by Django 5.2.5 on 2025-09-09 02:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0010_comment_likes_alter_comment_body'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
