# Generated by Django 5.2.5 on 2025-09-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0013_alter_comment_likes_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like_post', 'いいね（投稿）'), ('like_comment', 'いいね（コメント）'), ('comment', 'コメント'), ('follow', 'フォロー')], max_length=20),
        ),
    ]
