# Generated by Django 5.2.5 on 2025-09-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='amount',
            field=models.IntegerField(verbose_name='金額'),
        ),
    ]
